/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_learning_path.json.  Do not edit it directly.

#pragma once
#include "seeed_mt3620_mdb.h"

// Button A
#define BUTTON_A AILINK_WFM620RSC1_PIN3_GPIO6

// Button B
#define BUTTON_B AILINK_WFM620RSC1_PIN7_GPIO10

// LED 1
#define LED1 AILINK_WFM620RSC1_PIN4_GPIO7

// LED 2
#define LED2 AILINK_WFM620RSC1_PIN15_GPIO33

// Network Connected
#define NETWORK_CONNECTED_LED AILINK_WFM620RSC1_PIN16_GPIO35

// MT3620 RDB: Grove Relay
#define RELAY AILINK_WFM620RSC1_PIN14_GPIO31

// AVNET Start Kit Definition
#define I2cMaster2 AILINK_WFM620RSC1_ISU1_I2C

// AVNET Start Kit Definition
#define Adc0 AILINK_WFM620RSC1_ADC_CONTROLLER0

// AVNET Start Kit Definition
#define OEM_SEEED_STUDIO AILINK_WFM620RSC1_PIN3_GPIO6

