/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_learning_path.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// MT3620 RDB: Button A
#define BUTTON_A MT3620_RDB_BUTTON_A

// MT3620 RDB: Button B
#define BUTTON_B MT3620_RDB_BUTTON_B

// MT3620 RDB: LED 1
#define LED1 MT3620_RDB_LED1_GREEN

// MT3620 RDB: LED 2
#define LED2 MT3620_RDB_LED4_BLUE

// MT3620 RDB: Network Connected
#define NETWORK_CONNECTED_LED MT3620_RDB_NETWORKING_LED_RED

// MT3620 RDB: Grove Relay
#define RELAY MT3620_RDB_HEADER1_PIN4_GPIO

// ISU0 UART is exposed on header 2, pin 1 (RX), pin 3 (TX), pin 5 (CTS), pin 7 (RTS)
#define UART0 MT3620_RDB_HEADER2_ISU0_UART

// ISU0 I2C is exposed on header 2, pin 1 (SDA) and pin 7 (SCL)
#define I2cMaster2 MT3620_RDB_HEADER2_ISU0_I2C

// MT3620 ADC CONTROLLER 0: channel 0 on pin 41, channel 1 on pin 42, channel 2 on pin 43, channel 3 on pin 44, channel 4 on pin 45, channel 5 on pin 46, channel 6 on pin 47, and channel 7 on pin 48. Pins for this controller are shared with GPIO41, GPIO42, GPIO43, GPIO44, GPIO45, GPIO46, GPIO47 and GPIO48. If this ADC controller is requested, none of these GPIOs can be used.
#define Adc MT3620_RDB_ADC_CONTROLLER0

// MT3620 RDB: LED 1
#define LED_RED MT3620_RDB_LED1_RED

// MT3620 RDB: LED 1
#define LED_GREEN MT3620_RDB_LED1_GREEN

// MT3620 RDB: LED 1
#define LED_BLUE MT3620_RDB_LED1_BLUE

